version: "3"
services:
  fastapi-pypi-proxy:
    build:
      context: ./
      dockerfile: Dockerfile
    image: fastapi_pypi_proxy
    container_name: fastapi_pypi_proxy
    ports:
      - 8000:8000
    environment:
      PYPI_PROXY_PACKAGE_DIR: /PYPI_PROXY_PACKAGE_DIR
      PYPI_PROXY_LOG_DIR: /PYPI_PROXY_LOG_DIR
      PYPI_PROXY_LOG_LEVEL: ERROR
      PYPI_SOURCE: https://pypi.doubanio.com
